#!/bin/bash

CWD=$(pwd)

LIB_DIR=$CWD/lib/

export HADOOP_USER_CLASSPATH_FIRST=true
export HADOOP_CLASSPATH=lib/*:conf/

hadoop jar lib/dga-giraph-0.0.1.jar com.soteradefense.dga.DGARunner $LIB_DIR "${@:1}" -yj "annotations-2.0.2.jar,bval-jsr303-0.5.jar,dga-core-0.0.1.jar,guice-multibindings-3.0.jar,json-20090211.jar,netty-all-4.0.14.Final.jar,slice-0.5.jar,swift-service-0.13.1.jar,yjp-controller-api-redist-11.0.10.jar,asm-all-4.1.jar,cglib-nodep-2.2.2.jar,dga-giraph-0.0.1.jar,jackson-annotations-2.1.4.jar,jython-2.5.3.jar,nifty-client-0.13.1.jar,stats-0.91.jar,typetools-0.2.1.jar,base64-2.3.8.jar,commons-lang3-3.1.jar,fastutil-6.5.4.jar,jmxutils-1.16.jar,metrics-core-2.2.0.jar,nifty-core-0.13.1.jar,swift-annotations-0.13.1.jar,units-0.91.jar,bval-core-0.5.jar,configuration-0.91.jar,giraph-core-1.1.0-SNAPSHOT.jar,jol-core-0.1.jar,netty-3.7.0.Final.jar,paranamer-2.5.2.jar,swift-codec-0.13.1.jar,validation-api-1.1.0.Final.jar"
